apiVersion: extensions/v1beta1
kind: "Deployment"
metadata:
  name: "refapp"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: "refapp"
    spec:
      volumes:
      - name: semantic-configs
        hostPath:
          path: /semantic
      imagePullSecrets:
      - name: "groupby-registry"
      containers:
        - image: "docker.groupbyinc.com/quickstart-java:<version>"
          name: "refapp"
          ports:
          - containerPort: 8080
            name: "search"
